BUG23582924: Fix array append operation of mysqlx.ModifyStatement
Using array_append with ModifyStatement results in AttributeError:
AttributeError: 'EnumTypeWrapper' object has no attribute 'ARRAY_APPEND'

`ARRAY_APPEND` is an enum value of `MySQLxCrud.UpdateOperation`.
Removing `UpdateType` from `MySQLxCrud.UpdateOperation.UpdateType`
resolves the issue.

Tests were added for regression.