BUG21530100: Fix reading option files
During iteration of a dictionary, deleting of a key from the
dictionary causes the following exception:

RuntimeError: dictionary changed size during iteration

This happens because `dict.keys` returns iterable views in
python 3 instead of copies like in python 2.

Using Python Dictionary Comprehension's fixes this issue.

Test has been added for regression.