django: fix method signature of `display_name`
This is a partial revert of ddf6b13704e0e409bb8cac292acc42928501ab46
Django expects this method to take one argument, if it takes none a TypeError is thrown when running migrations.
```
TypeError: DatabaseWrapper.display_name() takes 0 positional arguments but 1 was given
```