BUG20324089: Fix HASH based sharding with MySQL Fabric
We fix HASH based sharding which was causing the following
runtime error:

    ValueError: Unsupported sharding type HASH

A unit test has been added for BUG#20324089.
(cherry picked from commit 0f7a8e7)