BUG23729357: Fix fetching BIT datatype
Firing a select query on a table having a BIT datatype results in the
following error:
ValueError: Unknown column type None

Adding the check for ColumnProtoType.BIT fixes this issue.

Test case was added for regression.