BUG23622215: Fix missing arguments in transaction methods
The following error is thrown on using any of the transaction methods:
TypeError: execute_nonquery() takes at least 3 arguments (2 given)

Adding the required arguments in the call to `execute_nonquery` from
each of the transaction methods.

Test cases were added for regression.