BUG26174214: Close connection when session isn't established
When using python versions < 2.7.9 and ssl, the connector throws the following
error:

InterfaceError: Invalid message

This is because the connector tries to close a session when the session has
not been established yet. The correct action in this case would be to close
the connection instead.