Keep the same with the converter function in django/db/models/sql/compiler.py in the new version of django.
[File /opt/env/talk/lib/python3.7/site-packages/django/db/models/sql/compiler.py, line 1081, in apply_converters
     value = converter(value, expression, connection)
TypeError: convert_booleanfield_value() missing 1 required positional argument:'context']